version: "3" 

services: 
    backend: 
        container_name: "express_server" 
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8000:8080"

    frontend:
        stdin_open: true
        container_name: "react_web"
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports: 
            - "3000:3000"
    
    database:
        container_name: "mongo_store"
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db
                
volumes:
    mongodb_data_container: